version: "3.3"
services:
  web_vue:
    image: node:8.9.4-alpine
    command: sh -c "npm install && npm run serve"
    working_dir: /usr/app/client/
    volumes:
      - ./client:/usr/app/client/:cached
    depends_on:
      - postgres
      - web_express
    restart: always
    ports:
      - "8080:8080"
  web_express:
    image: node:8.9.4-alpine
    command: sh -c "npm install && npm run dev"
    working_dir: /usr/app/
    volumes:
      - .:/usr/app/:cached
    depends_on:
      - postgres
    restart: always
    environment:
      DATABASE_URL: postgres://user@postgres:5432/test
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "5858:5858"
  postgres:
    image: postgres:10.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: test
